[package]
name = "carsync"
version = "0.1.0"
edition = "2024"
authors = ["Diplo2by <contactdarshanv@gmail.com>"]
description = "CarSync - rsync with cars!"
readme = "README.md"
license = "GPL-3.0"
keywords = ["rsync", "sync", "files", "cli", "backup"]
categories = ["command-line-utilities", "filesystem"]
repository = "https://github.com/Diplo2by/carsync"
homepage = "https://github.com/Diplo2by/carsync"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
console = "0.16.1"
indicatif = "0.18.1"
memmap2 = "0.9.9"
rayon = "1.11.0"
sha2 = "0.10.9"
walkdir = "2.5.0"
